#ifndef YDKJEXTRACTOR_PROPERTIES_H
#define YDKJEXTRACTOR_PROPERTIES_H

#define FOREACH_PROPERTY(PROPERTY) \
        PROPERTY(IMAGE_FORMAT)   \
        PROPERTY(IMAGE_PALETTE)  \
        PROPERTY(_LAST_PROPERTY) \

#define FOREACH_PROPERTY_VALUE(PROPVAL) \
    PROPVAL(IMAGE_FORMAT_BMP)  \
    PROPVAL(IMAGE_FOMRAT_PNG)   \
    PROPVAL(_LAST_PROPVAL) \

#define GENERATE_ENUM(ENUM) ENUM,
#define GENERATE_STRING(STRING) #STRING,

typedef enum {
    FOREACH_PROPERTY(GENERATE_ENUM)
} libsrf_property_t;


typedef enum {
    FOREACH_PROPERTY_VALUE(GENERATE_ENUM)
} libsrf_property_value_t;

extern const char *LIBSRF_PROPERTY_STRING[];
extern const char *LIBSRF_PROPERTY_VALUE_STRING[];

#endif //YDKJEXTRACTOR_PROPERTIES_H
